
FROM java:8-jre

ENV VERTICLE_FILE vero-1.0-SNAPSHOT-fat.jar

ENV VERTICLE_HOME /usr/vero

EXPOSE 8080

COPY $VERTICLE_FILE $VERTICLE_HOME/

WORKDIR $VERTICLE_HOME
ENTRYPOINT ["sh", "-c"]
CMD ["exec java -jar $VERTICLE_FILE"]